// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterDetailsInitParameters struct {

	// The name of the cluster device
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// An object that has node0 details
	Node0 []Node0InitParameters `json:"node0,omitempty" tf:"node0,omitempty"`

	// An object that has node1 details
	Node1 []Node1InitParameters `json:"node1,omitempty" tf:"node1,omitempty"`
}

type ClusterDetailsObservation struct {

	// The id of the cluster
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// The name of the cluster device
	ClusterName *string `json:"clusterName,omitempty" tf:"cluster_name,omitempty"`

	// An object that has node0 details
	Node0 []Node0Observation `json:"node0,omitempty" tf:"node0,omitempty"`

	// An object that has node1 details
	Node1 []Node1Observation `json:"node1,omitempty" tf:"node1,omitempty"`

	// The number of nodes in the cluster
	NumOfNodes *float64 `json:"numOfNodes,omitempty" tf:"num_of_nodes,omitempty"`
}

type ClusterDetailsParameters struct {

	// The name of the cluster device
	// +kubebuilder:validation:Optional
	ClusterName *string `json:"clusterName" tf:"cluster_name,omitempty"`

	// An object that has node0 details
	// +kubebuilder:validation:Optional
	Node0 []Node0Parameters `json:"node0" tf:"node0,omitempty"`

	// An object that has node1 details
	// +kubebuilder:validation:Optional
	Node1 []Node1Parameters `json:"node1" tf:"node1,omitempty"`
}

type DeviceInitParameters struct {

	// Unique identifier of applied ACL template
	ACLTemplateID *string `json:"aclTemplateId,omitempty" tf:"acl_template_id,omitempty"`

	// Device billing account number
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Additional Internet bandwidth, in Mbps, that will be allocated to the device
	AdditionalBandwidth *float64 `json:"additionalBandwidth,omitempty" tf:"additional_bandwidth,omitempty"`

	// Boolean value that determines device licensing mode: bring your own license or subscription (default)
	Byol *bool `json:"byol,omitempty" tf:"byol,omitempty"`

	// Unique identifier of applied cloud init file
	CloudInitFileID *string `json:"cloudInitFileId,omitempty" tf:"cloud_init_file_id,omitempty"`

	// An object that has the cluster details
	ClusterDetails []ClusterDetailsInitParameters `json:"clusterDetails,omitempty" tf:"cluster_details,omitempty"`

	// Parameter to identify internet access for device. Supported Values: INTERNET-ACCESS(default) or PRIVATE or INTERNET-ACCESS-WITH-PRVT-MGMT
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`

	// Number of CPU cores used by device
	CoreCount *float64 `json:"coreCount,omitempty" tf:"core_count,omitempty"`

	// Unique ID of an existing device
	DiverseDeviceID *string `json:"diverseDeviceId,omitempty" tf:"diverse_device_id,omitempty"`

	// Device hostname prefix
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Number of network interfaces on a device. If not specified, default number for a given device type will be used
	InterfaceCount *float64 `json:"interfaceCount,omitempty" tf:"interface_count,omitempty"`

	// Path to the license file that will be uploaded and applied on a device, applicable for some device types in BYOL licensing mode
	LicenseFile *string `json:"licenseFile,omitempty" tf:"license_file,omitempty"`

	// Unique identifier of applied license file
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License Token applicable for some device types in BYOL licensing mode
	LicenseToken *string `json:"licenseToken,omitempty" tf:"license_token,omitempty"`

	// Device location metro code
	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Unique identifier of applied MGMT ACL template
	MgmtACLTemplateUUID *string `json:"mgmtAclTemplateUuid,omitempty" tf:"mgmt_acl_template_uuid,omitempty"`

	// Device name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of email addresses that will receive device status notifications
	// +listType=set
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// Name/number used to identify device order on the invoice
	OrderReference *string `json:"orderReference,omitempty" tf:"order_reference,omitempty"`

	// Device software package code
	PackageCode *string `json:"packageCode,omitempty" tf:"package_code,omitempty"`

	// The unique identifier of Project Resource to which device is scoped to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Purchase order number associated with a device order
	PurchaseOrderNumber *string `json:"purchaseOrderNumber,omitempty" tf:"purchase_order_number,omitempty"`

	// Definition of SSH key that will be provisioned on a device
	SSHKey []DeviceSSHKeyInitParameters `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// Definition of secondary device applicable for HA setup
	SecondaryDevice []SecondaryDeviceInitParameters `json:"secondaryDevice,omitempty" tf:"secondary_device,omitempty"`

	// Boolean value that determines device management mode: self-managed or subscription (default)
	SelfManaged *bool `json:"selfManaged,omitempty" tf:"self_managed,omitempty"`

	// Device term length
	TermLength *float64 `json:"termLength,omitempty" tf:"term_length,omitempty"`

	// Device license throughput
	Throughput *float64 `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Device license throughput unit (Mbps or Gbps)
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`

	// Device type code
	TypeCode *string `json:"typeCode,omitempty" tf:"type_code,omitempty"`

	// Map of vendor specific configuration parameters for a device (controller1, activationKey, managementType, siteId, systemIpAddress)
	// +mapType=granular
	VendorConfiguration map[string]*string `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`

	// Device software software version
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// device interface id picked for WAN
	WanInterfaceID *string `json:"wanInterfaceId,omitempty" tf:"wan_interface_id,omitempty"`
}

type DeviceObservation struct {

	// Unique identifier of applied ACL template
	ACLTemplateID *string `json:"aclTemplateId,omitempty" tf:"acl_template_id,omitempty"`

	// Device billing account number
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Additional Internet bandwidth, in Mbps, that will be allocated to the device
	AdditionalBandwidth *float64 `json:"additionalBandwidth,omitempty" tf:"additional_bandwidth,omitempty"`

	// Autonomous system number
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// Boolean value that determines device licensing mode: bring your own license or subscription (default)
	Byol *bool `json:"byol,omitempty" tf:"byol,omitempty"`

	// Unique identifier of applied cloud init file
	CloudInitFileID *string `json:"cloudInitFileId,omitempty" tf:"cloud_init_file_id,omitempty"`

	// An object that has the cluster details
	ClusterDetails []ClusterDetailsObservation `json:"clusterDetails,omitempty" tf:"cluster_details,omitempty"`

	// Parameter to identify internet access for device. Supported Values: INTERNET-ACCESS(default) or PRIVATE or INTERNET-ACCESS-WITH-PRVT-MGMT
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`

	// Number of CPU cores used by device
	CoreCount *float64 `json:"coreCount,omitempty" tf:"core_count,omitempty"`

	// Unique ID of an existing device
	DiverseDeviceID *string `json:"diverseDeviceId,omitempty" tf:"diverse_device_id,omitempty"`

	// Diverse Device Name of an existing device
	DiverseDeviceName *string `json:"diverseDeviceName,omitempty" tf:"diverse_device_name,omitempty"`

	// Device hostname prefix
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Device location Equinix Business Exchange name
	Ibx *string `json:"ibx,omitempty" tf:"ibx,omitempty"`

	// List of device interfaces
	Interface []InterfaceObservation `json:"interface,omitempty" tf:"interface,omitempty"`

	// Number of network interfaces on a device. If not specified, default number for a given device type will be used
	InterfaceCount *float64 `json:"interfaceCount,omitempty" tf:"interface_count,omitempty"`

	// Path to the license file that will be uploaded and applied on a device, applicable for some device types in BYOL licensing mode
	LicenseFile *string `json:"licenseFile,omitempty" tf:"license_file,omitempty"`

	// Unique identifier of applied license file
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// Device license registration status
	LicenseStatus *string `json:"licenseStatus,omitempty" tf:"license_status,omitempty"`

	// License Token applicable for some device types in BYOL licensing mode
	LicenseToken *string `json:"licenseToken,omitempty" tf:"license_token,omitempty"`

	// Device location metro code
	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Unique identifier of applied MGMT ACL template
	MgmtACLTemplateUUID *string `json:"mgmtAclTemplateUuid,omitempty" tf:"mgmt_acl_template_uuid,omitempty"`

	// Device name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of email addresses that will receive device status notifications
	// +listType=set
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// Name/number used to identify device order on the invoice
	OrderReference *string `json:"orderReference,omitempty" tf:"order_reference,omitempty"`

	// Device software package code
	PackageCode *string `json:"packageCode,omitempty" tf:"package_code,omitempty"`

	// The unique identifier of Project Resource to which device is scoped to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Purchase order number associated with a device order
	PurchaseOrderNumber *string `json:"purchaseOrderNumber,omitempty" tf:"purchase_order_number,omitempty"`

	// Device redundancy type applicable for HA devices, either primary or secondary
	RedundancyType *string `json:"redundancyType,omitempty" tf:"redundancy_type,omitempty"`

	// Unique identifier for a redundant device, applicable for HA device
	RedundantID *string `json:"redundantId,omitempty" tf:"redundant_id,omitempty"`

	// Device location region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// IP address of SSH enabled interface on the device
	SSHIPAddress *string `json:"sshIpAddress,omitempty" tf:"ssh_ip_address,omitempty"`

	// FQDN of SSH enabled interface on the device
	SSHIPFqdn *string `json:"sshIpFqdn,omitempty" tf:"ssh_ip_fqdn,omitempty"`

	// Definition of SSH key that will be provisioned on a device
	SSHKey []DeviceSSHKeyObservation `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// Definition of secondary device applicable for HA setup
	SecondaryDevice []SecondaryDeviceObservation `json:"secondaryDevice,omitempty" tf:"secondary_device,omitempty"`

	// Boolean value that determines device management mode: self-managed or subscription (default)
	SelfManaged *bool `json:"selfManaged,omitempty" tf:"self_managed,omitempty"`

	// Device provisioning status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Device term length
	TermLength *float64 `json:"termLength,omitempty" tf:"term_length,omitempty"`

	// Device license throughput
	Throughput *float64 `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Device license throughput unit (Mbps or Gbps)
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`

	// Device type code
	TypeCode *string `json:"typeCode,omitempty" tf:"type_code,omitempty"`

	// Device unique identifier
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Map of vendor specific configuration parameters for a device (controller1, activationKey, managementType, siteId, systemIpAddress)
	// +mapType=granular
	VendorConfiguration map[string]*string `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`

	// Device software software version
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// device interface id picked for WAN
	WanInterfaceID *string `json:"wanInterfaceId,omitempty" tf:"wan_interface_id,omitempty"`

	// Device location zone code
	ZoneCode *string `json:"zoneCode,omitempty" tf:"zone_code,omitempty"`
}

type DeviceParameters struct {

	// Unique identifier of applied ACL template
	// +kubebuilder:validation:Optional
	ACLTemplateID *string `json:"aclTemplateId,omitempty" tf:"acl_template_id,omitempty"`

	// Device billing account number
	// +kubebuilder:validation:Optional
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Additional Internet bandwidth, in Mbps, that will be allocated to the device
	// +kubebuilder:validation:Optional
	AdditionalBandwidth *float64 `json:"additionalBandwidth,omitempty" tf:"additional_bandwidth,omitempty"`

	// Boolean value that determines device licensing mode: bring your own license or subscription (default)
	// +kubebuilder:validation:Optional
	Byol *bool `json:"byol,omitempty" tf:"byol,omitempty"`

	// Unique identifier of applied cloud init file
	// +kubebuilder:validation:Optional
	CloudInitFileID *string `json:"cloudInitFileId,omitempty" tf:"cloud_init_file_id,omitempty"`

	// An object that has the cluster details
	// +kubebuilder:validation:Optional
	ClusterDetails []ClusterDetailsParameters `json:"clusterDetails,omitempty" tf:"cluster_details,omitempty"`

	// Parameter to identify internet access for device. Supported Values: INTERNET-ACCESS(default) or PRIVATE or INTERNET-ACCESS-WITH-PRVT-MGMT
	// +kubebuilder:validation:Optional
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`

	// Number of CPU cores used by device
	// +kubebuilder:validation:Optional
	CoreCount *float64 `json:"coreCount,omitempty" tf:"core_count,omitempty"`

	// Unique ID of an existing device
	// +kubebuilder:validation:Optional
	DiverseDeviceID *string `json:"diverseDeviceId,omitempty" tf:"diverse_device_id,omitempty"`

	// Device hostname prefix
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Number of network interfaces on a device. If not specified, default number for a given device type will be used
	// +kubebuilder:validation:Optional
	InterfaceCount *float64 `json:"interfaceCount,omitempty" tf:"interface_count,omitempty"`

	// Path to the license file that will be uploaded and applied on a device, applicable for some device types in BYOL licensing mode
	// +kubebuilder:validation:Optional
	LicenseFile *string `json:"licenseFile,omitempty" tf:"license_file,omitempty"`

	// Unique identifier of applied license file
	// +kubebuilder:validation:Optional
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License Token applicable for some device types in BYOL licensing mode
	// +kubebuilder:validation:Optional
	LicenseToken *string `json:"licenseToken,omitempty" tf:"license_token,omitempty"`

	// Device location metro code
	// +kubebuilder:validation:Optional
	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Unique identifier of applied MGMT ACL template
	// +kubebuilder:validation:Optional
	MgmtACLTemplateUUID *string `json:"mgmtAclTemplateUuid,omitempty" tf:"mgmt_acl_template_uuid,omitempty"`

	// Device name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of email addresses that will receive device status notifications
	// +kubebuilder:validation:Optional
	// +listType=set
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// Name/number used to identify device order on the invoice
	// +kubebuilder:validation:Optional
	OrderReference *string `json:"orderReference,omitempty" tf:"order_reference,omitempty"`

	// Device software package code
	// +kubebuilder:validation:Optional
	PackageCode *string `json:"packageCode,omitempty" tf:"package_code,omitempty"`

	// The unique identifier of Project Resource to which device is scoped to
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Purchase order number associated with a device order
	// +kubebuilder:validation:Optional
	PurchaseOrderNumber *string `json:"purchaseOrderNumber,omitempty" tf:"purchase_order_number,omitempty"`

	// Definition of SSH key that will be provisioned on a device
	// +kubebuilder:validation:Optional
	SSHKey []DeviceSSHKeyParameters `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// Definition of secondary device applicable for HA setup
	// +kubebuilder:validation:Optional
	SecondaryDevice []SecondaryDeviceParameters `json:"secondaryDevice,omitempty" tf:"secondary_device,omitempty"`

	// Boolean value that determines device management mode: self-managed or subscription (default)
	// +kubebuilder:validation:Optional
	SelfManaged *bool `json:"selfManaged,omitempty" tf:"self_managed,omitempty"`

	// Device term length
	// +kubebuilder:validation:Optional
	TermLength *float64 `json:"termLength,omitempty" tf:"term_length,omitempty"`

	// Device license throughput
	// +kubebuilder:validation:Optional
	Throughput *float64 `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Device license throughput unit (Mbps or Gbps)
	// +kubebuilder:validation:Optional
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`

	// Device type code
	// +kubebuilder:validation:Optional
	TypeCode *string `json:"typeCode,omitempty" tf:"type_code,omitempty"`

	// Map of vendor specific configuration parameters for a device (controller1, activationKey, managementType, siteId, systemIpAddress)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	VendorConfiguration map[string]*string `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`

	// Device software software version
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// device interface id picked for WAN
	// +kubebuilder:validation:Optional
	WanInterfaceID *string `json:"wanInterfaceId,omitempty" tf:"wan_interface_id,omitempty"`
}

type DeviceSSHKeyInitParameters struct {

	// Reference by name to previously provisioned public SSH key
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Username associated with given key
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type DeviceSSHKeyObservation struct {

	// Reference by name to previously provisioned public SSH key
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Username associated with given key
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type DeviceSSHKeyParameters struct {

	// Reference by name to previously provisioned public SSH key
	// +kubebuilder:validation:Optional
	KeyName *string `json:"keyName" tf:"key_name,omitempty"`

	// Username associated with given key
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

type InterfaceInitParameters struct {
}

type InterfaceObservation struct {
	AssignedType *string `json:"assignedType,omitempty" tf:"assigned_type,omitempty"`

	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OperationalStatus *string `json:"operationalStatus,omitempty" tf:"operational_status,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type InterfaceParameters struct {
}

type Node0InitParameters struct {

	// License file id. This is necessary for Fortinet and Juniper clusters
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License token. This is necessary for Palo Alto clusters
	LicenseTokenSecretRef *v1.LocalSecretKeySelector `json:"licenseTokenSecretRef,omitempty" tf:"-"`

	// An object that has fields relevant to the vendor of the cluster device
	VendorConfiguration []VendorConfigurationInitParameters `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`
}

type Node0Observation struct {

	// License file id. This is necessary for Fortinet and Juniper clusters
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// The name of the node
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The unique id of the node
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// An object that has fields relevant to the vendor of the cluster device
	VendorConfiguration []VendorConfigurationObservation `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`
}

type Node0Parameters struct {

	// License file id. This is necessary for Fortinet and Juniper clusters
	// +kubebuilder:validation:Optional
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License token. This is necessary for Palo Alto clusters
	// +kubebuilder:validation:Optional
	LicenseTokenSecretRef *v1.LocalSecretKeySelector `json:"licenseTokenSecretRef,omitempty" tf:"-"`

	// An object that has fields relevant to the vendor of the cluster device
	// +kubebuilder:validation:Optional
	VendorConfiguration []VendorConfigurationParameters `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`
}

type Node1InitParameters struct {

	// License file id. This is necessary for Fortinet and Juniper clusters
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License token. This is necessary for Palo Alto clusters
	LicenseTokenSecretRef *v1.LocalSecretKeySelector `json:"licenseTokenSecretRef,omitempty" tf:"-"`

	// An object that has fields relevant to the vendor of the cluster device
	VendorConfiguration []Node1VendorConfigurationInitParameters `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`
}

type Node1Observation struct {

	// License file id. This is necessary for Fortinet and Juniper clusters
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// The name of the node
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The unique id of the node
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// An object that has fields relevant to the vendor of the cluster device
	VendorConfiguration []Node1VendorConfigurationObservation `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`
}

type Node1Parameters struct {

	// License file id. This is necessary for Fortinet and Juniper clusters
	// +kubebuilder:validation:Optional
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License token. This is necessary for Palo Alto clusters
	// +kubebuilder:validation:Optional
	LicenseTokenSecretRef *v1.LocalSecretKeySelector `json:"licenseTokenSecretRef,omitempty" tf:"-"`

	// An object that has fields relevant to the vendor of the cluster device
	// +kubebuilder:validation:Optional
	VendorConfiguration []Node1VendorConfigurationParameters `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`
}

type Node1VendorConfigurationInitParameters struct {

	// Activation key. This is required for Velocloud clusters
	ActivationKeySecretRef *v1.LocalSecretKeySelector `json:"activationKeySecretRef,omitempty" tf:"-"`

	// The administrative password of the device. You can use it to log in to the console. This field is not available for all device types
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// System IP Address. Mandatory for the Fortinet SDWAN cluster device
	Controller1 *string `json:"controller1,omitempty" tf:"controller1,omitempty"`

	// Controller fqdn. This is required for Velocloud clusters
	ControllerFqdn *string `json:"controllerFqdn,omitempty" tf:"controller_fqdn,omitempty"`

	// Hostname. This is necessary for Palo Alto, Juniper, and Fortinet clusters
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// License id. This field is relevant only for the BlueCat DNS and DHCP Server
	LicenseIDSecretRef *v1.LocalSecretKeySelector `json:"licenseIdSecretRef,omitempty" tf:"-"`

	// License key. This field is relevant only for the BlueCat DNS and DHCP Server
	LicenseKeySecretRef *v1.LocalSecretKeySelector `json:"licenseKeySecretRef,omitempty" tf:"-"`

	// Panorama Server Auth Key. This field is relevant only for Palo Alto Networks Firewall devices
	PanoramaAuthKeySecretRef *v1.LocalSecretKeySelector `json:"panoramaAuthKeySecretRef,omitempty" tf:"-"`

	// Panorama Server IP Address. This field is relevant only for Palo Alto Networks Firewall devices
	PanoramaIPAddress *string `json:"panoramaIpAddress,omitempty" tf:"panorama_ip_address,omitempty"`

	// Private address. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateAddress *string `json:"privateAddress,omitempty" tf:"private_address,omitempty"`

	// Private CIDR Mask. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateCidrMask *string `json:"privateCidrMask,omitempty" tf:"private_cidr_mask,omitempty"`

	// Private gateway. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateGateway *string `json:"privateGateway,omitempty" tf:"private_gateway,omitempty"`

	// The CLI password of the device. This field is relevant only for the Velocloud SDWAN cluster
	RootPasswordSecretRef *v1.LocalSecretKeySelector `json:"rootPasswordSecretRef,omitempty" tf:"-"`
}

type Node1VendorConfigurationObservation struct {

	// System IP Address. Mandatory for the Fortinet SDWAN cluster device
	Controller1 *string `json:"controller1,omitempty" tf:"controller1,omitempty"`

	// Controller fqdn. This is required for Velocloud clusters
	ControllerFqdn *string `json:"controllerFqdn,omitempty" tf:"controller_fqdn,omitempty"`

	// Hostname. This is necessary for Palo Alto, Juniper, and Fortinet clusters
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Panorama Server IP Address. This field is relevant only for Palo Alto Networks Firewall devices
	PanoramaIPAddress *string `json:"panoramaIpAddress,omitempty" tf:"panorama_ip_address,omitempty"`

	// Private address. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateAddress *string `json:"privateAddress,omitempty" tf:"private_address,omitempty"`

	// Private CIDR Mask. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateCidrMask *string `json:"privateCidrMask,omitempty" tf:"private_cidr_mask,omitempty"`

	// Private gateway. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateGateway *string `json:"privateGateway,omitempty" tf:"private_gateway,omitempty"`
}

type Node1VendorConfigurationParameters struct {

	// Activation key. This is required for Velocloud clusters
	// +kubebuilder:validation:Optional
	ActivationKeySecretRef *v1.LocalSecretKeySelector `json:"activationKeySecretRef,omitempty" tf:"-"`

	// The administrative password of the device. You can use it to log in to the console. This field is not available for all device types
	// +kubebuilder:validation:Optional
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// System IP Address. Mandatory for the Fortinet SDWAN cluster device
	// +kubebuilder:validation:Optional
	Controller1 *string `json:"controller1,omitempty" tf:"controller1,omitempty"`

	// Controller fqdn. This is required for Velocloud clusters
	// +kubebuilder:validation:Optional
	ControllerFqdn *string `json:"controllerFqdn,omitempty" tf:"controller_fqdn,omitempty"`

	// Hostname. This is necessary for Palo Alto, Juniper, and Fortinet clusters
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// License id. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	LicenseIDSecretRef *v1.LocalSecretKeySelector `json:"licenseIdSecretRef,omitempty" tf:"-"`

	// License key. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	LicenseKeySecretRef *v1.LocalSecretKeySelector `json:"licenseKeySecretRef,omitempty" tf:"-"`

	// Panorama Server Auth Key. This field is relevant only for Palo Alto Networks Firewall devices
	// +kubebuilder:validation:Optional
	PanoramaAuthKeySecretRef *v1.LocalSecretKeySelector `json:"panoramaAuthKeySecretRef,omitempty" tf:"-"`

	// Panorama Server IP Address. This field is relevant only for Palo Alto Networks Firewall devices
	// +kubebuilder:validation:Optional
	PanoramaIPAddress *string `json:"panoramaIpAddress,omitempty" tf:"panorama_ip_address,omitempty"`

	// Private address. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	PrivateAddress *string `json:"privateAddress,omitempty" tf:"private_address,omitempty"`

	// Private CIDR Mask. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	PrivateCidrMask *string `json:"privateCidrMask,omitempty" tf:"private_cidr_mask,omitempty"`

	// Private gateway. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	PrivateGateway *string `json:"privateGateway,omitempty" tf:"private_gateway,omitempty"`

	// The CLI password of the device. This field is relevant only for the Velocloud SDWAN cluster
	// +kubebuilder:validation:Optional
	RootPasswordSecretRef *v1.LocalSecretKeySelector `json:"rootPasswordSecretRef,omitempty" tf:"-"`
}

type SSHKeyInitParameters struct {

	// Reference by name to previously provisioned public SSH key
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Username associated with given key
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SSHKeyObservation struct {

	// Reference by name to previously provisioned public SSH key
	KeyName *string `json:"keyName,omitempty" tf:"key_name,omitempty"`

	// Username associated with given key
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type SSHKeyParameters struct {

	// Reference by name to previously provisioned public SSH key
	// +kubebuilder:validation:Optional
	KeyName *string `json:"keyName" tf:"key_name,omitempty"`

	// Username associated with given key
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

type SecondaryDeviceInitParameters struct {

	// Unique identifier of applied ACL template
	ACLTemplateID *string `json:"aclTemplateId,omitempty" tf:"acl_template_id,omitempty"`

	// Device billing account number
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Additional Internet bandwidth, in Mbps, that will be allocated to the device
	AdditionalBandwidth *float64 `json:"additionalBandwidth,omitempty" tf:"additional_bandwidth,omitempty"`

	// Unique identifier of applied cloud init file
	CloudInitFileID *string `json:"cloudInitFileId,omitempty" tf:"cloud_init_file_id,omitempty"`

	// Device hostname prefix
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Path to the license file that will be uploaded and applied on a device, applicable for some device types in BYOL licensing mode
	LicenseFile *string `json:"licenseFile,omitempty" tf:"license_file,omitempty"`

	// Unique identifier of applied license file
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License Token applicable for some device types in BYOL licensing mode
	LicenseToken *string `json:"licenseToken,omitempty" tf:"license_token,omitempty"`

	// Device location metro code
	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Unique identifier of applied MGMT ACL template
	MgmtACLTemplateUUID *string `json:"mgmtAclTemplateUuid,omitempty" tf:"mgmt_acl_template_uuid,omitempty"`

	// Device name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of email addresses that will receive device status notifications
	// +listType=set
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// Definition of SSH key that will be provisioned on a device
	SSHKey []SSHKeyInitParameters `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// Map of vendor specific configuration parameters for a device (controller1, activationKey, managementType, siteId, systemIpAddress)
	// +mapType=granular
	VendorConfiguration map[string]*string `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`

	// device interface id picked for WAN
	WanInterfaceID *string `json:"wanInterfaceId,omitempty" tf:"wan_interface_id,omitempty"`
}

type SecondaryDeviceInterfaceInitParameters struct {
}

type SecondaryDeviceInterfaceObservation struct {
	AssignedType *string `json:"assignedType,omitempty" tf:"assigned_type,omitempty"`

	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OperationalStatus *string `json:"operationalStatus,omitempty" tf:"operational_status,omitempty"`

	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SecondaryDeviceInterfaceParameters struct {
}

type SecondaryDeviceObservation struct {

	// Unique identifier of applied ACL template
	ACLTemplateID *string `json:"aclTemplateId,omitempty" tf:"acl_template_id,omitempty"`

	// Device billing account number
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Additional Internet bandwidth, in Mbps, that will be allocated to the device
	AdditionalBandwidth *float64 `json:"additionalBandwidth,omitempty" tf:"additional_bandwidth,omitempty"`

	// Autonomous system number
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// Unique identifier of applied cloud init file
	CloudInitFileID *string `json:"cloudInitFileId,omitempty" tf:"cloud_init_file_id,omitempty"`

	// Device hostname prefix
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Device location Equinix Business Exchange name
	Ibx *string `json:"ibx,omitempty" tf:"ibx,omitempty"`

	// List of device interfaces
	Interface []SecondaryDeviceInterfaceObservation `json:"interface,omitempty" tf:"interface,omitempty"`

	// Path to the license file that will be uploaded and applied on a device, applicable for some device types in BYOL licensing mode
	LicenseFile *string `json:"licenseFile,omitempty" tf:"license_file,omitempty"`

	// Unique identifier of applied license file
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// Device license registration status
	LicenseStatus *string `json:"licenseStatus,omitempty" tf:"license_status,omitempty"`

	// License Token applicable for some device types in BYOL licensing mode
	LicenseToken *string `json:"licenseToken,omitempty" tf:"license_token,omitempty"`

	// Device location metro code
	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Unique identifier of applied MGMT ACL template
	MgmtACLTemplateUUID *string `json:"mgmtAclTemplateUuid,omitempty" tf:"mgmt_acl_template_uuid,omitempty"`

	// Device name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// List of email addresses that will receive device status notifications
	// +listType=set
	Notifications []*string `json:"notifications,omitempty" tf:"notifications,omitempty"`

	// The unique identifier of Project Resource to which device is scoped to
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Device redundancy type applicable for HA devices, either primary or secondary
	RedundancyType *string `json:"redundancyType,omitempty" tf:"redundancy_type,omitempty"`

	// Unique identifier for a redundant device, applicable for HA device
	RedundantID *string `json:"redundantId,omitempty" tf:"redundant_id,omitempty"`

	// Device location region
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// IP address of SSH enabled interface on the device
	SSHIPAddress *string `json:"sshIpAddress,omitempty" tf:"ssh_ip_address,omitempty"`

	// FQDN of SSH enabled interface on the device
	SSHIPFqdn *string `json:"sshIpFqdn,omitempty" tf:"ssh_ip_fqdn,omitempty"`

	// Definition of SSH key that will be provisioned on a device
	SSHKey []SSHKeyObservation `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// Device provisioning status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Device unique identifier
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`

	// Map of vendor specific configuration parameters for a device (controller1, activationKey, managementType, siteId, systemIpAddress)
	// +mapType=granular
	VendorConfiguration map[string]*string `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`

	// device interface id picked for WAN
	WanInterfaceID *string `json:"wanInterfaceId,omitempty" tf:"wan_interface_id,omitempty"`

	// Device location zone code
	ZoneCode *string `json:"zoneCode,omitempty" tf:"zone_code,omitempty"`
}

type SecondaryDeviceParameters struct {

	// Unique identifier of applied ACL template
	// +kubebuilder:validation:Optional
	ACLTemplateID *string `json:"aclTemplateId,omitempty" tf:"acl_template_id,omitempty"`

	// Device billing account number
	// +kubebuilder:validation:Optional
	AccountNumber *string `json:"accountNumber" tf:"account_number,omitempty"`

	// Additional Internet bandwidth, in Mbps, that will be allocated to the device
	// +kubebuilder:validation:Optional
	AdditionalBandwidth *float64 `json:"additionalBandwidth,omitempty" tf:"additional_bandwidth,omitempty"`

	// Unique identifier of applied cloud init file
	// +kubebuilder:validation:Optional
	CloudInitFileID *string `json:"cloudInitFileId,omitempty" tf:"cloud_init_file_id,omitempty"`

	// Device hostname prefix
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Path to the license file that will be uploaded and applied on a device, applicable for some device types in BYOL licensing mode
	// +kubebuilder:validation:Optional
	LicenseFile *string `json:"licenseFile,omitempty" tf:"license_file,omitempty"`

	// Unique identifier of applied license file
	// +kubebuilder:validation:Optional
	LicenseFileID *string `json:"licenseFileId,omitempty" tf:"license_file_id,omitempty"`

	// License Token applicable for some device types in BYOL licensing mode
	// +kubebuilder:validation:Optional
	LicenseToken *string `json:"licenseToken,omitempty" tf:"license_token,omitempty"`

	// Device location metro code
	// +kubebuilder:validation:Optional
	MetroCode *string `json:"metroCode" tf:"metro_code,omitempty"`

	// Unique identifier of applied MGMT ACL template
	// +kubebuilder:validation:Optional
	MgmtACLTemplateUUID *string `json:"mgmtAclTemplateUuid,omitempty" tf:"mgmt_acl_template_uuid,omitempty"`

	// Device name
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// List of email addresses that will receive device status notifications
	// +kubebuilder:validation:Optional
	// +listType=set
	Notifications []*string `json:"notifications" tf:"notifications,omitempty"`

	// Definition of SSH key that will be provisioned on a device
	// +kubebuilder:validation:Optional
	SSHKey []SSHKeyParameters `json:"sshKey,omitempty" tf:"ssh_key,omitempty"`

	// Map of vendor specific configuration parameters for a device (controller1, activationKey, managementType, siteId, systemIpAddress)
	// +kubebuilder:validation:Optional
	// +mapType=granular
	VendorConfiguration map[string]*string `json:"vendorConfiguration,omitempty" tf:"vendor_configuration,omitempty"`

	// device interface id picked for WAN
	// +kubebuilder:validation:Optional
	WanInterfaceID *string `json:"wanInterfaceId,omitempty" tf:"wan_interface_id,omitempty"`
}

type VendorConfigurationInitParameters struct {

	// Activation key. This is required for Velocloud clusters
	ActivationKeySecretRef *v1.LocalSecretKeySelector `json:"activationKeySecretRef,omitempty" tf:"-"`

	// The administrative password of the device. You can use it to log in to the console. This field is not available for all device types
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// System IP Address. Mandatory for the Fortinet SDWAN cluster device
	Controller1 *string `json:"controller1,omitempty" tf:"controller1,omitempty"`

	// Controller fqdn. This is required for Velocloud clusters
	ControllerFqdn *string `json:"controllerFqdn,omitempty" tf:"controller_fqdn,omitempty"`

	// Hostname. This is necessary for Palo Alto, Juniper, and Fortinet clusters
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// License id. This field is relevant only for the BlueCat DNS and DHCP Server
	LicenseIDSecretRef *v1.LocalSecretKeySelector `json:"licenseIdSecretRef,omitempty" tf:"-"`

	// License key. This field is relevant only for the BlueCat DNS and DHCP Server
	LicenseKeySecretRef *v1.LocalSecretKeySelector `json:"licenseKeySecretRef,omitempty" tf:"-"`

	// Panorama Server Auth Key. This field is relevant only for Palo Alto Networks Firewall devices
	PanoramaAuthKeySecretRef *v1.LocalSecretKeySelector `json:"panoramaAuthKeySecretRef,omitempty" tf:"-"`

	// Panorama Server IP Address. This field is relevant only for Palo Alto Networks Firewall devices
	PanoramaIPAddress *string `json:"panoramaIpAddress,omitempty" tf:"panorama_ip_address,omitempty"`

	// Private address. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateAddress *string `json:"privateAddress,omitempty" tf:"private_address,omitempty"`

	// Private CIDR Mask. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateCidrMask *string `json:"privateCidrMask,omitempty" tf:"private_cidr_mask,omitempty"`

	// Private gateway. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateGateway *string `json:"privateGateway,omitempty" tf:"private_gateway,omitempty"`

	// The CLI password of the device. This field is relevant only for the Velocloud SDWAN cluster
	RootPasswordSecretRef *v1.LocalSecretKeySelector `json:"rootPasswordSecretRef,omitempty" tf:"-"`
}

type VendorConfigurationObservation struct {

	// System IP Address. Mandatory for the Fortinet SDWAN cluster device
	Controller1 *string `json:"controller1,omitempty" tf:"controller1,omitempty"`

	// Controller fqdn. This is required for Velocloud clusters
	ControllerFqdn *string `json:"controllerFqdn,omitempty" tf:"controller_fqdn,omitempty"`

	// Hostname. This is necessary for Palo Alto, Juniper, and Fortinet clusters
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Panorama Server IP Address. This field is relevant only for Palo Alto Networks Firewall devices
	PanoramaIPAddress *string `json:"panoramaIpAddress,omitempty" tf:"panorama_ip_address,omitempty"`

	// Private address. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateAddress *string `json:"privateAddress,omitempty" tf:"private_address,omitempty"`

	// Private CIDR Mask. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateCidrMask *string `json:"privateCidrMask,omitempty" tf:"private_cidr_mask,omitempty"`

	// Private gateway. This field is relevant only for the BlueCat DNS and DHCP Server
	PrivateGateway *string `json:"privateGateway,omitempty" tf:"private_gateway,omitempty"`
}

type VendorConfigurationParameters struct {

	// Activation key. This is required for Velocloud clusters
	// +kubebuilder:validation:Optional
	ActivationKeySecretRef *v1.LocalSecretKeySelector `json:"activationKeySecretRef,omitempty" tf:"-"`

	// The administrative password of the device. You can use it to log in to the console. This field is not available for all device types
	// +kubebuilder:validation:Optional
	AdminPasswordSecretRef *v1.LocalSecretKeySelector `json:"adminPasswordSecretRef,omitempty" tf:"-"`

	// System IP Address. Mandatory for the Fortinet SDWAN cluster device
	// +kubebuilder:validation:Optional
	Controller1 *string `json:"controller1,omitempty" tf:"controller1,omitempty"`

	// Controller fqdn. This is required for Velocloud clusters
	// +kubebuilder:validation:Optional
	ControllerFqdn *string `json:"controllerFqdn,omitempty" tf:"controller_fqdn,omitempty"`

	// Hostname. This is necessary for Palo Alto, Juniper, and Fortinet clusters
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// License id. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	LicenseIDSecretRef *v1.LocalSecretKeySelector `json:"licenseIdSecretRef,omitempty" tf:"-"`

	// License key. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	LicenseKeySecretRef *v1.LocalSecretKeySelector `json:"licenseKeySecretRef,omitempty" tf:"-"`

	// Panorama Server Auth Key. This field is relevant only for Palo Alto Networks Firewall devices
	// +kubebuilder:validation:Optional
	PanoramaAuthKeySecretRef *v1.LocalSecretKeySelector `json:"panoramaAuthKeySecretRef,omitempty" tf:"-"`

	// Panorama Server IP Address. This field is relevant only for Palo Alto Networks Firewall devices
	// +kubebuilder:validation:Optional
	PanoramaIPAddress *string `json:"panoramaIpAddress,omitempty" tf:"panorama_ip_address,omitempty"`

	// Private address. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	PrivateAddress *string `json:"privateAddress,omitempty" tf:"private_address,omitempty"`

	// Private CIDR Mask. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	PrivateCidrMask *string `json:"privateCidrMask,omitempty" tf:"private_cidr_mask,omitempty"`

	// Private gateway. This field is relevant only for the BlueCat DNS and DHCP Server
	// +kubebuilder:validation:Optional
	PrivateGateway *string `json:"privateGateway,omitempty" tf:"private_gateway,omitempty"`

	// The CLI password of the device. This field is relevant only for the Velocloud SDWAN cluster
	// +kubebuilder:validation:Optional
	RootPasswordSecretRef *v1.LocalSecretKeySelector `json:"rootPasswordSecretRef,omitempty" tf:"-"`
}

// DeviceSpec defines the desired state of Device
type DeviceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DeviceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeviceInitParameters `json:"initProvider,omitempty"`
}

// DeviceStatus defines the observed state of Device.
type DeviceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeviceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Device is the Schema for the Devices API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,equinix}
type Device struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountNumber) || (has(self.initProvider) && has(self.initProvider.accountNumber))",message="spec.forProvider.accountNumber is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.coreCount) || (has(self.initProvider) && has(self.initProvider.coreCount))",message="spec.forProvider.coreCount is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.metroCode) || (has(self.initProvider) && has(self.initProvider.metroCode))",message="spec.forProvider.metroCode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.notifications) || (has(self.initProvider) && has(self.initProvider.notifications))",message="spec.forProvider.notifications is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.packageCode) || (has(self.initProvider) && has(self.initProvider.packageCode))",message="spec.forProvider.packageCode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.termLength) || (has(self.initProvider) && has(self.initProvider.termLength))",message="spec.forProvider.termLength is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.typeCode) || (has(self.initProvider) && has(self.initProvider.typeCode))",message="spec.forProvider.typeCode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.version) || (has(self.initProvider) && has(self.initProvider.version))",message="spec.forProvider.version is a required parameter"
	Spec   DeviceSpec   `json:"spec"`
	Status DeviceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeviceList contains a list of Devices
type DeviceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Device `json:"items"`
}

// Repository type metadata.
var (
	Device_Kind             = "Device"
	Device_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Device_Kind}.String()
	Device_KindAPIVersion   = Device_Kind + "." + CRDGroupVersion.String()
	Device_GroupVersionKind = CRDGroupVersion.WithKind(Device_Kind)
)

func init() {
	SchemeBuilder.Register(&Device{}, &DeviceList{})
}
