// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DeviceLinkDeviceInitParameters struct {

	// Device ASN number
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// Device identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Device network interface identifier to use for device link connection
	InterfaceID *float64 `json:"interfaceId,omitempty" tf:"interface_id,omitempty"`
}

type DeviceLinkDeviceObservation struct {

	// Device ASN number
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// Device identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Assigned IP address from device link subnet
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Device network interface identifier to use for device link connection
	InterfaceID *float64 `json:"interfaceId,omitempty" tf:"interface_id,omitempty"`

	// Device link connection provisioning status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type DeviceLinkDeviceParameters struct {

	// Device ASN number
	// +kubebuilder:validation:Optional
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// Device identifier
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// Device network interface identifier to use for device link connection
	// +kubebuilder:validation:Optional
	InterfaceID *float64 `json:"interfaceId,omitempty" tf:"interface_id,omitempty"`
}

type DeviceLinkInitParameters struct {
	Device []DeviceLinkDeviceInitParameters `json:"device,omitempty" tf:"device,omitempty"`

	// Definition of one or more, inter metro connections belonging to the device link
	Link []LinkInitParameters `json:"link,omitempty" tf:"link,omitempty"`

	// Definition of one or more, inter or intra metro connections belonging to the device link
	MetroLink []MetroLinkInitParameters `json:"metroLink,omitempty" tf:"metro_link,omitempty"`

	// Device link name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// project_id
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Optional) Whether the connection should be created through Fabric's primary or secondary port. Supported values: `PRIMARY` (Default), `SECONDARY`, `HYBRID`
	RedundancyType *string `json:"redundancyType,omitempty" tf:"redundancy_type,omitempty"`

	// Device link subnet CIDR.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type DeviceLinkObservation struct {
	Device []DeviceLinkDeviceObservation `json:"device,omitempty" tf:"device,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Definition of one or more, inter metro connections belonging to the device link
	Link []LinkObservation `json:"link,omitempty" tf:"link,omitempty"`

	// Definition of one or more, inter or intra metro connections belonging to the device link
	MetroLink []MetroLinkObservation `json:"metroLink,omitempty" tf:"metro_link,omitempty"`

	// Device link name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// project_id
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Optional) Whether the connection should be created through Fabric's primary or secondary port. Supported values: `PRIMARY` (Default), `SECONDARY`, `HYBRID`
	RedundancyType *string `json:"redundancyType,omitempty" tf:"redundancy_type,omitempty"`

	// Device link provisioning status
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Device link subnet CIDR.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// Device link unique identifier
	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type DeviceLinkParameters struct {

	// +kubebuilder:validation:Optional
	Device []DeviceLinkDeviceParameters `json:"device,omitempty" tf:"device,omitempty"`

	// Definition of one or more, inter metro connections belonging to the device link
	// +kubebuilder:validation:Optional
	Link []LinkParameters `json:"link,omitempty" tf:"link,omitempty"`

	// Definition of one or more, inter or intra metro connections belonging to the device link
	// +kubebuilder:validation:Optional
	MetroLink []MetroLinkParameters `json:"metroLink,omitempty" tf:"metro_link,omitempty"`

	// Device link name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// project_id
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Optional) Whether the connection should be created through Fabric's primary or secondary port. Supported values: `PRIMARY` (Default), `SECONDARY`, `HYBRID`
	// +kubebuilder:validation:Optional
	RedundancyType *string `json:"redundancyType,omitempty" tf:"redundancy_type,omitempty"`

	// Device link subnet CIDR.
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type LinkInitParameters struct {

	// Billing account number to be used for connection charges
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Connection destination metro code
	DstMetroCode *string `json:"dstMetroCode,omitempty" tf:"dst_metro_code,omitempty"`

	// Connection destination zone code
	DstZoneCode *string `json:"dstZoneCode,omitempty" tf:"dst_zone_code,omitempty"`

	// Connection source metro code
	SrcMetroCode *string `json:"srcMetroCode,omitempty" tf:"src_metro_code,omitempty"`

	// Connection source zone code
	SrcZoneCode *string `json:"srcZoneCode,omitempty" tf:"src_zone_code,omitempty"`

	// Connection throughput
	Throughput *string `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Connection throughput unit
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`
}

type LinkObservation struct {

	// Billing account number to be used for connection charges
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	// Connection destination metro code
	DstMetroCode *string `json:"dstMetroCode,omitempty" tf:"dst_metro_code,omitempty"`

	// Connection destination zone code
	DstZoneCode *string `json:"dstZoneCode,omitempty" tf:"dst_zone_code,omitempty"`

	// Connection source metro code
	SrcMetroCode *string `json:"srcMetroCode,omitempty" tf:"src_metro_code,omitempty"`

	// Connection source zone code
	SrcZoneCode *string `json:"srcZoneCode,omitempty" tf:"src_zone_code,omitempty"`

	// Connection throughput
	Throughput *string `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Connection throughput unit
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`
}

type LinkParameters struct {

	// Billing account number to be used for connection charges
	// +kubebuilder:validation:Optional
	AccountNumber *string `json:"accountNumber" tf:"account_number,omitempty"`

	// Connection destination metro code
	// +kubebuilder:validation:Optional
	DstMetroCode *string `json:"dstMetroCode" tf:"dst_metro_code,omitempty"`

	// Connection destination zone code
	// +kubebuilder:validation:Optional
	DstZoneCode *string `json:"dstZoneCode,omitempty" tf:"dst_zone_code,omitempty"`

	// Connection source metro code
	// +kubebuilder:validation:Optional
	SrcMetroCode *string `json:"srcMetroCode" tf:"src_metro_code,omitempty"`

	// Connection source zone code
	// +kubebuilder:validation:Optional
	SrcZoneCode *string `json:"srcZoneCode,omitempty" tf:"src_zone_code,omitempty"`

	// Connection throughput
	// +kubebuilder:validation:Optional
	Throughput *string `json:"throughput" tf:"throughput,omitempty"`

	// Connection throughput unit
	// +kubebuilder:validation:Optional
	ThroughputUnit *string `json:"throughputUnit" tf:"throughput_unit,omitempty"`
}

type MetroLinkInitParameters struct {

	// Billing account number to be used for connection charges
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Connection throughput
	Throughput *string `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Connection throughput unit
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`
}

type MetroLinkObservation struct {

	// Billing account number to be used for connection charges
	AccountNumber *string `json:"accountNumber,omitempty" tf:"account_number,omitempty"`

	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// Connection throughput
	Throughput *string `json:"throughput,omitempty" tf:"throughput,omitempty"`

	// Connection throughput unit
	ThroughputUnit *string `json:"throughputUnit,omitempty" tf:"throughput_unit,omitempty"`
}

type MetroLinkParameters struct {

	// Billing account number to be used for connection charges
	// +kubebuilder:validation:Optional
	AccountNumber *string `json:"accountNumber" tf:"account_number,omitempty"`

	// +kubebuilder:validation:Optional
	MetroCode *string `json:"metroCode" tf:"metro_code,omitempty"`

	// Connection throughput
	// +kubebuilder:validation:Optional
	Throughput *string `json:"throughput" tf:"throughput,omitempty"`

	// Connection throughput unit
	// +kubebuilder:validation:Optional
	ThroughputUnit *string `json:"throughputUnit" tf:"throughput_unit,omitempty"`
}

// DeviceLinkSpec defines the desired state of DeviceLink
type DeviceLinkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DeviceLinkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeviceLinkInitParameters `json:"initProvider,omitempty"`
}

// DeviceLinkStatus defines the observed state of DeviceLink.
type DeviceLinkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeviceLinkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DeviceLink is the Schema for the DeviceLinks API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,equinix}
type DeviceLink struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.device) || (has(self.initProvider) && has(self.initProvider.device))",message="spec.forProvider.device is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DeviceLinkSpec   `json:"spec"`
	Status DeviceLinkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeviceLinkList contains a list of DeviceLinks
type DeviceLinkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DeviceLink `json:"items"`
}

// Repository type metadata.
var (
	DeviceLink_Kind             = "DeviceLink"
	DeviceLink_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DeviceLink_Kind}.String()
	DeviceLink_KindAPIVersion   = DeviceLink_Kind + "." + CRDGroupVersion.String()
	DeviceLink_GroupVersionKind = CRDGroupVersion.WithKind(DeviceLink_Kind)
)

func init() {
	SchemeBuilder.Register(&DeviceLink{}, &DeviceLinkList{})
}
