// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ACLTemplate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *BGP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Device) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DeviceLink) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSHUser) Hub() {}
